import { pgTable, uuid, varchar, numeric, integer, text, timestamp, jsonb } from 'drizzle-orm/pg-core';

export const salesOrders = pgTable('sales_orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  storeId: uuid('store_id').notNull(),
  registerId: uuid('register_id'),
  shiftId: uuid('shift_id'),
  orderCode: varchar('order_code', { length: 80 }).notNull().unique(),
  orderType: varchar('order_type', { length: 30 }).notNull().default('pos'),
  status: varchar('status', { length: 30 }).notNull().default('open'),
  cashierId: uuid('cashier_id'),
  customerId: uuid('customer_id'),
  customerName: varchar('customer_name', { length: 200 }),
  subTotal: numeric('sub_total', { precision: 18, scale: 2 }).notNull().default('0'),
  discountAmount: numeric('discount_amount', { precision: 18, scale: 2 }).notNull().default('0'),
  taxAmount: numeric('tax_amount', { precision: 18, scale: 2 }).notNull().default('0'),
  grandTotal: numeric('grand_total', { precision: 18, scale: 2 }).notNull().default('0'),
  paidAmount: numeric('paid_amount', { precision: 18, scale: 2 }).notNull().default('0'),
  changeAmount: numeric('change_amount', { precision: 18, scale: 2 }).notNull().default('0'),
  paymentStatus: varchar('payment_status', { length: 30 }).notNull().default('unpaid'),
  fulfillmentStatus: varchar('fulfillment_status', { length: 30 }).notNull().default('pending'),
  sourceChannel: varchar('source_channel', { length: 50 }).notNull().default('pos'),
  note: text('note'),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
  cancelReason: text('cancel_reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// DB table = sales_order_lines
export const salesOrderItems = pgTable('sales_order_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').notNull(),
  productId: uuid('product_id').notNull(),
  variantId: uuid('variant_id'),
  productName: varchar('product_name', { length: 255 }),
  quantity: numeric('quantity', { precision: 18, scale: 4 }).notNull(),
  unitName: varchar('unit_name', { length: 50 }).notNull(),
  unitPrice: numeric('unit_price', { precision: 18, scale: 2 }).notNull(),
  costPrice: numeric('cost_price', { precision: 18, scale: 2 }).notNull().default('0'),
  discountAmount: numeric('discount_amount', { precision: 18, scale: 2 }).notNull().default('0'),
  taxAmount: numeric('tax_amount', { precision: 18, scale: 2 }).notNull().default('0'),
  lineTotal: numeric('line_total', { precision: 18, scale: 2 }).notNull(),
  modifiers: jsonb('modifiers').notNull().default([]),
  kitchenStatus: varchar('kitchen_status', { length: 20 }).notNull().default('pending'),
  note: text('note'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const orderPayments = pgTable('order_payments', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').notNull(),
  paymentMethodId: uuid('payment_method_id'),
  methodCode: varchar('method_code', { length: 50 }).notNull(),
  methodName: varchar('method_name', { length: 100 }).notNull(),
  amount: numeric('amount', { precision: 18, scale: 2 }).notNull(),
  tenderAmount: numeric('tender_amount', { precision: 18, scale: 2 }),
  changeAmount: numeric('change_amount', { precision: 18, scale: 2 }).notNull().default('0'),
  transactionRef: varchar('transaction_ref', { length: 150 }),
  status: varchar('status', { length: 20 }).notNull().default('completed'),
  paidAt: timestamp('paid_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
