/**
 * AUTO-GENERATED by scripts/db-sync.js — DO NOT EDIT
 * Re-run: node scripts/db-sync.js --platform
 */
export * from './schema';
export * from './relations';

// ─── Auth & Accounts ─────────────────────────────────────────────
export {
  accountsInPlatform as accounts,
  authSessionsInPlatform as authSessions,
  accountMfaMethodsInPlatform as accountMfaMethods,
  accountBusinessesInPlatform as accountBusinesses,
  accountBranchAccessInPlatform as accountBranchAccess,
  impersonationSessionsInPlatform as impersonationSessions,
  sessionLimitsInPlatform as sessionLimits,
} from './schema';

// ─── Businesses & Branches ───────────────────────────────────────
export {
  businessesInPlatform as businesses,
  businessBranchesInPlatform as businessBranches,
  businessModulesInPlatform as businessModules,
  businessSubscriptionsInPlatform as businessSubscriptions,
} from './schema';

// ─── Billing & Subscriptions ─────────────────────────────────────
export {
  subscriptionPlansInPlatform as subscriptionPlans,
  planLimitsInPlatform as planLimits,
  billingEventsInPlatform as billingEvents,
  platformInvoicesInPlatform as platformInvoices,
  platformInvoiceLinesInPlatform as platformInvoiceLines,
  platformPaymentsInPlatform as platformPayments,
  renewalKeysInPlatform as renewalKeys,
  usageBillingItemsInPlatform as usageBillingItems,
  businessUsageCountersInPlatform as businessUsageCounters,
  businessUsageDailyInPlatform as businessUsageDaily,
} from './schema';

// ─── Platform RBAC ───────────────────────────────────────────────
export {
  rolesInPlatform as roles,
  permissionsInPlatform as permissions,
  rolePermissionsInPlatform as rolePermissions,
  accountRoleBindingsInPlatform as accountRoleBindings,
} from './schema';

// ─── Support ─────────────────────────────────────────────────────
export {
  supportTicketsInPlatform as supportTickets,
  supportTicketMessagesInPlatform as supportTicketMessages,
} from './schema';

// ─── Webhooks ────────────────────────────────────────────────────
export {
  webhookEndpointsInPlatform as webhookEndpoints,
  webhookSubscriptionsInPlatform as webhookSubscriptions,
  webhookDeliveryLogsInPlatform as webhookDeliveryLogs,
} from './schema';

// ─── System & Audit ──────────────────────────────────────────────
export {
  auditEventsInPlatform as auditEvents,
  platformAuditLogInPlatform as platformAuditLog,
  platformAnnouncementsInPlatform as platformAnnouncements,
  systemSettingsInPlatform as systemSettings,
  migrationLogInPlatform as migrationLog,
  flywaySchemaHistoryInPlatform as flywaySchemaHistory,
} from './schema';

// ─── API & Devices ───────────────────────────────────────────────
export {
  apiClientsInPlatform as apiClients,
  deviceIdentitiesInPlatform as deviceIdentities,
} from './schema';

// ─── Reference Data ──────────────────────────────────────────────
export {
  bankMasterInPlatform as bankMaster,
} from './schema';
