/**
 * AUTO-GENERATED by scripts/db-sync.js — DO NOT EDIT
 * Re-run: node scripts/db-sync.js --business
 */
export * from './schema';
export * from './relations';

// ─── Store & Device ──────────────────────────────────────────────
export {
  storesInBusinessTemplate as stores,
  storeConfigsInBusinessTemplate as storeConfigs,
  registersInBusinessTemplate as registers,
  deviceBindingsInBusinessTemplate as deviceBindings,
  floorPlansInBusinessTemplate as floorPlans,
  diningTablesInBusinessTemplate as diningTables,
  kitchenStationsInBusinessTemplate as kitchenStations,
  printerDevicesInBusinessTemplate as printerDevices,
  salesChannelsInBusinessTemplate as salesChannels,
} from './schema';

// ─── Staff & RBAC ────────────────────────────────────────────────
export {
  staffMembersInBusinessTemplate as staffMembers,
  staffAccountLinksInBusinessTemplate as staffAccountLinks,
  staffRoleBindingsInBusinessTemplate as staffRoleBindings,
  rolesInBusinessTemplate as roles,
  permissionsInBusinessTemplate as permissions,
  rolePermissionsInBusinessTemplate as rolePermissions,
  permissionDefinitionsInBusinessTemplate as permissionDefinitions,
  permissionChangeHistoryInBusinessTemplate as permissionChangeHistory,
  roleChangeHistoryInBusinessTemplate as roleChangeHistory,
  temporaryPermissionGrantsInBusinessTemplate as temporaryPermissionGrants,
  workShiftsInBusinessTemplate as workShifts,
  timekeepingLogsInBusinessTemplate as timekeepingLogs,
  departmentsInBusinessTemplate as departments,
  payrollPeriodsInBusinessTemplate as payrollPeriods,
  payrollItemsInBusinessTemplate as payrollItems,
} from './schema';

// ─── Customer & CRM ──────────────────────────────────────────────
export {
  customersInBusinessTemplate as customers,
  customerAddressesInBusinessTemplate as customerAddresses,
  customerGroupsInBusinessTemplate as customerGroups,
  customerSegmentsInBusinessTemplate as customerSegments,
  customerTagsInBusinessTemplate as customerTags,
  customerTagMappingsInBusinessTemplate as customerTagMappings,
  customerInteractionsInBusinessTemplate as customerInteractions,
  customerContactPreferencesInBusinessTemplate as customerContactPreferences,
  customerConsentsInBusinessTemplate as customerConsents,
  customerMergeRequestsInBusinessTemplate as customerMergeRequests,
  customerCreditProfilesInBusinessTemplate as customerCreditProfiles,
} from './schema';

// ─── Loyalty & Wallet ────────────────────────────────────────────
export {
  loyaltyProgramsInBusinessTemplate as loyaltyPrograms,
  loyaltyTiersInBusinessTemplate as loyaltyTiers,
  loyaltyPointTransactionsInBusinessTemplate as loyaltyPointTransactions,
  customerWalletsInBusinessTemplate as customerWallets,
  walletTransactionsInBusinessTemplate as walletTransactions,
  customerVouchersInBusinessTemplate as customerVouchers,
  voucherBatchesInBusinessTemplate as voucherBatches,
  giftCardsInBusinessTemplate as giftCards,
  giftCardTransactionsInBusinessTemplate as giftCardTransactions,
  customerReceivablesInBusinessTemplate as customerReceivables,
  customerReceivablePaymentsInBusinessTemplate as customerReceivablePayments,
  customerReceivableAdjustmentsInBusinessTemplate as customerReceivableAdjustments,
  customerReceivableAllocationsInBusinessTemplate as customerReceivableAllocations,
  customerLedgersInBusinessTemplate as customerLedgers,
} from './schema';

// ─── Catalog — Products ──────────────────────────────────────────
export {
  productsInBusinessTemplate as products,
  productVariantsInBusinessTemplate as productVariants,
  productBarcodesInBusinessTemplate as productBarcodes,
  productCategoriesInBusinessTemplate as productCategories,
  productAttributeGroupsInBusinessTemplate as productAttributeGroups,
  productAttributeValuesInBusinessTemplate as productAttributeValues,
  productTagsInBusinessTemplate as productTags,
  productTagMappingsInBusinessTemplate as productTagMappings,
  productRecipesInBusinessTemplate as productRecipes,
  productSerialsInBusinessTemplate as productSerials,
  productLotsInBusinessTemplate as productLots,
  productCostHistoryInBusinessTemplate as productCostHistory,
  productPriceHistoryInBusinessTemplate as productPriceHistory,
  productStoreSettingsInBusinessTemplate as productStoreSettings,
  productUnitsInBusinessTemplate as productUnits,
  comboItemsInBusinessTemplate as comboItems,
  ingredientConsumptionsInBusinessTemplate as ingredientConsumptions,
  unitsInBusinessTemplate as units,
  brandsInBusinessTemplate as brands,
} from './schema';

// ─── Pricing ─────────────────────────────────────────────────────
export {
  priceBooksInBusinessTemplate as priceBooks,
  priceBookItemsInBusinessTemplate as priceBookItems,
  discountsInBusinessTemplate as discounts,
  menuAvailabilityInBusinessTemplate as menuAvailability,
  taxClassesInBusinessTemplate as taxClasses,
} from './schema';

// ─── Inventory ───────────────────────────────────────────────────
export {
  stockLocationsInBusinessTemplate as stockLocations,
  stockBalancesInBusinessTemplate as stockBalances,
  stockLotBalancesInBusinessTemplate as stockLotBalances,
  stockTransactionsInBusinessTemplate as stockTransactions,
  stockReservationsInBusinessTemplate as stockReservations,
  stockRulesInBusinessTemplate as stockRules,
  stockTransfersInBusinessTemplate as stockTransfers,
  stockTransferItemsInBusinessTemplate as stockTransferItems,
  stocktakesInBusinessTemplate as stocktakes,
  stocktakeItemsInBusinessTemplate as stocktakeItems,
  stockValuationSnapshotsInBusinessTemplate as stockValuationSnapshots,
  inventoryCostLayersInBusinessTemplate as inventoryCostLayers,
  inventoryCostAdjustmentsInBusinessTemplate as inventoryCostAdjustments,
} from './schema';

// ─── Purchasing ──────────────────────────────────────────────────
export {
  suppliersInBusinessTemplate as suppliers,
  purchaseOrdersInBusinessTemplate as purchaseOrders,
  purchaseOrderLinesInBusinessTemplate as purchaseOrderLines,
  landedCostsInBusinessTemplate as landedCosts,
  landedCostAllocationsInBusinessTemplate as landedCostAllocations,
  supplierReturnsInBusinessTemplate as supplierReturns,
  supplierReturnLinesInBusinessTemplate as supplierReturnLines,
  supplierPayablesInBusinessTemplate as supplierPayables,
  supplierPaymentsInBusinessTemplate as supplierPayments,
  supplierPaymentAllocationsInBusinessTemplate as supplierPaymentAllocations,
  supplierCreditNotesInBusinessTemplate as supplierCreditNotes,
  debitNotesInBusinessTemplate as debitNotes,
  receivingDiscrepanciesInBusinessTemplate as receivingDiscrepancies,
  cogsAllocationsInBusinessTemplate as cogsAllocations,
} from './schema';

// ─── Orders & POS ────────────────────────────────────────────────
export {
  salesOrdersInBusinessTemplate as salesOrders,
  salesOrderLinesInBusinessTemplate as salesOrderLines,
  salesOrderAdjustmentsInBusinessTemplate as salesOrderAdjustments,
  salesOrderStatusHistoryInBusinessTemplate as salesOrderStatusHistory,
  orderPaymentsInBusinessTemplate as orderPayments,
  orderReturnsInBusinessTemplate as orderReturns,
  orderReturnLinesInBusinessTemplate as orderReturnLines,
  tableSessionsInBusinessTemplate as tableSessions,
  kitchenTicketsInBusinessTemplate as kitchenTickets,
  kitchenTicketLinesInBusinessTemplate as kitchenTicketLines,
  prepBatchesInBusinessTemplate as prepBatches,
  wasteLogsInBusinessTemplate as wasteLogs,
} from './schema';

// ─── Payments ────────────────────────────────────────────────────
export {
  paymentMethodsInBusinessTemplate as paymentMethods,
  paymentRefundsInBusinessTemplate as paymentRefunds,
  paymentReconciliationsInBusinessTemplate as paymentReconciliations,
  paymentReconciliationItemsInBusinessTemplate as paymentReconciliationItems,
  bankTransactionsInBusinessTemplate as bankTransactions,
  bankDepositsInBusinessTemplate as bankDeposits,
  bankStatementImportsInBusinessTemplate as bankStatementImports,
  codReconciliationsInBusinessTemplate as codReconciliations,
} from './schema';

// ─── Cashbook & Shifts ───────────────────────────────────────────
export {
  cashAccountsInBusinessTemplate as cashAccounts,
  cashTransactionsInBusinessTemplate as cashTransactions,
  cashDrawerMovementsInBusinessTemplate as cashDrawerMovements,
  cashDenominationsInBusinessTemplate as cashDenominations,
  shiftCashCountsInBusinessTemplate as shiftCashCounts,
  shiftPaymentSummariesInBusinessTemplate as shiftPaymentSummaries,
} from './schema';

// ─── Finance & Accounting ────────────────────────────────────────
export {
  chartOfAccountsInBusinessTemplate as chartOfAccounts,
  journalEntriesInBusinessTemplate as journalEntries,
  journalLinesInBusinessTemplate as journalLines,
  salesInvoicesInBusinessTemplate as salesInvoices,
  salesInvoiceLinesInBusinessTemplate as salesInvoiceLines,
  salesInvoiceTaxesInBusinessTemplate as salesInvoiceTaxes,
  invoiceNumberSequencesInBusinessTemplate as invoiceNumberSequences,
  creditNotesInBusinessTemplate as creditNotes,
  creditNoteLinesInBusinessTemplate as creditNoteLines,
  taxReportsInBusinessTemplate as taxReports,
  businessPeriodsInBusinessTemplate as businessPeriods,
  periodLocksInBusinessTemplate as periodLocks,
  closingRunsInBusinessTemplate as closingRuns,
  closingRunItemsInBusinessTemplate as closingRunItems,
  reopenPeriodRequestsInBusinessTemplate as reopenPeriodRequests,
} from './schema';

// ─── Reports ─────────────────────────────────────────────────────
export {
  reportDailySalesSnapshotsInBusinessTemplate as reportDailySalesSnapshots,
} from './schema';

// ─── Shipping & Fulfillment ──────────────────────────────────────
export {
  shipmentsInBusinessTemplate as shipments,
  shipmentItemsInBusinessTemplate as shipmentItems,
  shipmentPackagesInBusinessTemplate as shipmentPackages,
  shipmentTrackingEventsInBusinessTemplate as shipmentTrackingEvents,
  deliveryOrdersInBusinessTemplate as deliveryOrders,
  deliveryAttemptsInBusinessTemplate as deliveryAttempts,
  shippingCarriersInBusinessTemplate as shippingCarriers,
  channelOrderMappingsInBusinessTemplate as channelOrderMappings,
  channelProductMappingsInBusinessTemplate as channelProductMappings,
} from './schema';

// ─── Production & Kitchen ────────────────────────────────────────
export {
  productionOrdersInBusinessTemplate as productionOrders,
  productionOrderLinesInBusinessTemplate as productionOrderLines,
} from './schema';

// ─── Service & CRM+ ──────────────────────────────────────────────
export {
  campaignsInBusinessTemplate as campaigns,
  campaignMessagesInBusinessTemplate as campaignMessages,
  appointmentsInBusinessTemplate as appointments,
  appointmentLinesInBusinessTemplate as appointmentLines,
  serviceOrdersInBusinessTemplate as serviceOrders,
  serviceOrderLinesInBusinessTemplate as serviceOrderLines,
  servicePackagesInBusinessTemplate as servicePackages,
  warrantyClaimsInBusinessTemplate as warrantyClaims,
  warrantyPoliciesInBusinessTemplate as warrantyPolicies,
} from './schema';

// ─── System ──────────────────────────────────────────────────────
export {
  activityLogsInBusinessTemplate as activityLogs,
  appNotificationsInBusinessTemplate as appNotifications,
  approvalRequestsInBusinessTemplate as approvalRequests,
  documentSequencesInBusinessTemplate as documentSequences,
  eventOutboxInBusinessTemplate as eventOutbox,
  externalEventLogsInBusinessTemplate as externalEventLogs,
  idempotencyKeysInBusinessTemplate as idempotencyKeys,
  mediaAssetsInBusinessTemplate as mediaAssets,
  offlineSyncBatchesInBusinessTemplate as offlineSyncBatches,
  pushTokensInBusinessTemplate as pushTokens,
  realtimeEventsInBusinessTemplate as realtimeEvents,
  syncJobsInBusinessTemplate as syncJobs,
  syncJobLogsInBusinessTemplate as syncJobLogs,
  webhookInboxInBusinessTemplate as webhookInbox,
} from './schema';

// ─── Billing ─────────────────────────────────────────────────────
export {
  packageUsagesInBusinessTemplate as packageUsages,
} from './schema';
