
-- =====================================================================
-- FULL TENANT RBAC/PERMISSION SEED FOR NEW DATABASE
-- Run with: psql -v business_schema=business_template -f this_file.sql
-- =====================================================================
SET client_encoding TO 'UTF8';
SELECT set_config('search_path', :'business_schema' || ', platform, public', false);

-- Policy:
-- - permission_name: UTF-8 display text (Vietnamese allowed)
-- - role_key/permission_key: English machine key (ASCII)

INSERT INTO permissions(permission_key, permission_name, module_key) VALUES
  ('pos.enter', 'Vào POS', 'pos'),
  ('pos.open_register', 'Mở quầy POS', 'pos'),
  ('receipt.print', 'In hóa đơn', 'pos'),
  ('shift.open', 'Mở ca', 'shift'),
  ('shift.close', 'Đóng ca', 'shift'),
  ('shift.view', 'Xem ca', 'shift'),
  ('order.view', 'Xem đơn hàng', 'order'),
  ('order.create', 'Tạo đơn hàng', 'order'),
  ('order.update_draft', 'Sửa đơn nháp', 'order'),
  ('order.cancel', 'Hủy đơn', 'order'),
  ('order.void', 'Void đơn', 'order'),
  ('order.complete', 'Hoàn tất đơn', 'order'),
  ('order.discount.apply', 'Áp giảm giá', 'order'),
  ('order.price.override', 'Sửa giá tại POS', 'order'),
  ('order.sell_on_credit', 'Bán công nợ', 'order'),
  ('order.credit_override', 'Vượt hạn mức công nợ', 'order'),
  ('order.return', 'Trả hàng', 'order'),
  ('order.exchange', 'Đổi hàng', 'order'),
  ('order.split_bill', 'Tách bill', 'order'),
  ('order.merge_table', 'Gộp bàn', 'order'),
  ('order.move_table', 'Chuyển bàn', 'order'),
  ('payment.view', 'Xem thanh toán', 'payment'),
  ('payment.process', 'Xử lý thanh toán', 'payment'),
  ('payment.partial', 'Thanh toán một phần', 'payment'),
  ('payment.cash', 'Thanh toán tiền mặt', 'payment'),
  ('payment.bank_transfer', 'Thanh toán chuyển khoản', 'payment'),
  ('payment.card', 'Thanh toán thẻ', 'payment'),
  ('payment.e_wallet', 'Thanh toán ví', 'payment'),
  ('payment.voucher', 'Thanh toán voucher', 'payment'),
  ('payment.point', 'Thanh toán điểm', 'payment'),
  ('payment.refund', 'Hoàn tiền', 'payment'),
  ('payment.refund_override', 'Hoàn tiền vượt chính sách', 'payment'),
  ('payment.reconcile', 'Đối soát thanh toán', 'payment'),
  ('receivable.view', 'Xem công nợ KH', 'receivable'),
  ('receivable.create', 'Tạo công nợ KH', 'receivable'),
  ('receivable.collect', 'Thu công nợ KH', 'receivable'),
  ('receivable.adjust', 'Điều chỉnh công nợ KH', 'receivable'),
  ('receivable.write_off', 'Xóa nợ/xử lý nợ xấu', 'receivable'),
  ('receivable.export', 'Xuất công nợ', 'receivable'),
  ('store.view', 'Xem cửa hàng', 'store'),
  ('store.create', 'Tạo cửa hàng', 'store'),
  ('store.update', 'Sửa cửa hàng', 'store'),
  ('store.disable', 'Tắt cửa hàng', 'store'),
  ('store.config.update', 'Sửa cấu hình cửa hàng', 'store'),
  ('store.device.bind', 'Gán thiết bị POS', 'store'),
  ('staff.view', 'Xem nhân viên', 'staff'),
  ('staff.create', 'Tạo nhân viên', 'staff'),
  ('staff.update', 'Sửa nhân viên', 'staff'),
  ('staff.disable', 'Khóa nhân viên', 'staff'),
  ('staff.assign_store', 'Gán nhân viên vào store', 'staff'),
  ('staff.assign_role', 'Gán quyền nhân viên', 'staff'),
  ('staff.reset_pin', 'Reset PIN', 'staff'),
  ('staff.salary.view', 'Xem lương', 'staff'),
  ('staff.salary.update', 'Sửa lương', 'staff'),
  ('role.view', 'Xem role', 'rbac'),
  ('role.create', 'Tạo role', 'rbac'),
  ('role.update', 'Sửa role', 'rbac'),
  ('role.assign_permission', 'Gán permission', 'rbac'),
  ('product.view', 'Xem sản phẩm', 'product'),
  ('product.create', 'Tạo sản phẩm', 'product'),
  ('product.update', 'Sửa sản phẩm', 'product'),
  ('product.delete', 'Xóa sản phẩm', 'product'),
  ('product.import', 'Import sản phẩm', 'product'),
  ('product.export', 'Export sản phẩm', 'product'),
  ('product.price.update', 'Sửa giá bán', 'product'),
  ('product.cost.update', 'Sửa giá vốn', 'product'),
  ('product.barcode.manage', 'Quản lý barcode', 'product'),
  ('product.recipe.manage', 'Quản lý recipe/BOM', 'product'),
  ('product.lot.manage', 'Quản lý lô/hạn sử dụng', 'product'),
  ('product.serial.manage', 'Quản lý serial/IMEI', 'product'),
  ('product.media.manage', 'Quản lý media sản phẩm', 'product'),
  ('promotion.view', 'Xem khuyến mãi', 'promotion'),
  ('promotion.create', 'Tạo khuyến mãi', 'promotion'),
  ('promotion.update', 'Sửa khuyến mãi', 'promotion'),
  ('promotion.delete', 'Xóa khuyến mãi', 'promotion'),
  ('inventory.view', 'Xem tồn kho', 'inventory'),
  ('inventory.view_cost', 'Xem giá trị tồn kho', 'inventory'),
  ('inventory.reserve', 'Giữ hàng', 'inventory'),
  ('inventory.deduct', 'Trừ kho', 'inventory'),
  ('inventory.adjust', 'Điều chỉnh kho', 'inventory'),
  ('inventory.transfer', 'Chuyển kho', 'inventory'),
  ('inventory.transfer.approve', 'Duyệt chuyển kho', 'inventory'),
  ('inventory.stocktake', 'Kiểm kho', 'inventory'),
  ('inventory.stocktake.approve', 'Chốt kiểm kho', 'inventory'),
  ('inventory.transaction.view', 'Xem lịch sử kho', 'inventory'),
  ('inventory.costing.view', 'Xem costing', 'inventory'),
  ('inventory.costing.adjust', 'Điều chỉnh costing', 'inventory'),
  ('purchase.view', 'Xem đơn nhập', 'purchase'),
  ('purchase.create', 'Tạo đơn nhập', 'purchase'),
  ('purchase.receive', 'Nhận hàng', 'purchase'),
  ('purchase.cancel', 'Hủy đơn nhập', 'purchase'),
  ('purchase.return', 'Trả hàng NCC', 'purchase'),
  ('purchase.payable.view', 'Xem công nợ NCC', 'purchase'),
  ('purchase.payment.process', 'Thanh toán NCC', 'purchase'),
  ('supplier.view', 'Xem NCC', 'supplier'),
  ('supplier.create', 'Tạo NCC', 'supplier'),
  ('supplier.update', 'Sửa NCC', 'supplier'),
  ('supplier.disable', 'Khóa NCC', 'supplier'),
  ('customer.view', 'Xem khách hàng', 'customer'),
  ('customer.create', 'Tạo khách hàng', 'customer'),
  ('customer.update', 'Sửa khách hàng', 'customer'),
  ('customer.disable', 'Khóa khách hàng', 'customer'),
  ('customer.merge', 'Gộp khách hàng', 'customer'),
  ('customer.export', 'Xuất khách hàng', 'customer'),
  ('customer.point.adjust', 'Điều chỉnh điểm', 'customer'),
  ('customer.consent.update', 'Sửa consent', 'customer'),
  ('customer.campaign.manage', 'Quản lý chiến dịch', 'customer'),
  ('loyalty.view', 'Xem loyalty', 'loyalty'),
  ('loyalty.manage', 'Quản lý loyalty', 'loyalty'),
  ('wallet.view', 'Xem ví khách hàng', 'wallet'),
  ('wallet.adjust', 'Điều chỉnh ví khách hàng', 'wallet'),
  ('report.sales.view', 'Xem báo cáo doanh thu', 'report'),
  ('report.inventory.view', 'Xem báo cáo kho', 'report'),
  ('report.profit.view', 'Xem báo cáo lợi nhuận', 'report'),
  ('report.staff.view', 'Xem báo cáo nhân viên', 'report'),
  ('report.export', 'Xuất báo cáo', 'report'),
  ('report.cost_profit.view', 'Xem giá vốn/lợi nhuận', 'report'),
  ('invoice.view', 'Xem hóa đơn', 'invoice'),
  ('invoice.create', 'Tạo hóa đơn', 'invoice'),
  ('invoice.cancel', 'Hủy hóa đơn', 'invoice'),
  ('invoice.credit_note.create', 'Tạo credit note', 'invoice'),
  ('cash.view', 'Xem quỹ', 'cash'),
  ('cash.movement.create', 'Tạo giao dịch quỹ', 'cash'),
  ('cash.drawer.count', 'Đếm két', 'cash'),
  ('cash.drawer.reconcile', 'Đối soát két', 'cash'),
  ('cash.bank_deposit', 'Nộp tiền ngân hàng', 'cash'),
  ('finance.view', 'Xem tài chính', 'finance'),
  ('finance.journal.post', 'Ghi bút toán', 'finance'),
  ('finance.period.lock', 'Khóa kỳ', 'finance'),
  ('finance.period.reopen', 'Mở lại kỳ', 'finance'),
  ('setting.view', 'Xem cấu hình', 'setting'),
  ('setting.update', 'Sửa cấu hình', 'setting'),
  ('activity_log.view', 'Xem log hoạt động', 'audit'),
  ('approval.view', 'Xem yêu cầu duyệt', 'approval'),
  ('approval.approve', 'Duyệt yêu cầu', 'approval'),
  ('approval.reject', 'Từ chối yêu cầu', 'approval'),
  ('notification.view', 'Xem thông báo', 'notification'),
  ('notification.send', 'Gửi thông báo', 'notification'),
  ('channel.view', 'Xem kênh bán', 'channel'),
  ('channel.manage', 'Quản lý kênh bán', 'channel'),
  ('channel.sync', 'Đồng bộ kênh bán', 'channel'),
  ('shipping.view', 'Xem vận chuyển', 'shipping'),
  ('shipping.create', 'Tạo shipment', 'shipping'),
  ('shipping.update', 'Cập nhật shipment', 'shipping'),
  ('shipping.cod_reconcile', 'Đối soát COD', 'shipping'),
  ('service.view', 'Xem dịch vụ/bảo hành', 'service'),
  ('service.manage', 'Quản lý dịch vụ/bảo hành', 'service'),
  ('warranty.claim.process', 'Xử lý bảo hành', 'service'),
  ('production.view', 'Xem sản xuất/bếp', 'production'),
  ('production.manage', 'Quản lý sản xuất/bếp', 'production'),
  ('waste.create', 'Ghi nhận hao hụt', 'production'),
  ('kitchen.view', 'Xem bếp', 'kitchen'),
  ('kitchen.update', 'Cập nhật trạng thái bếp', 'kitchen'),
  ('table.view', 'Xem bàn', 'table'),
  ('table.manage', 'Quản lý bàn', 'table')
ON CONFLICT (permission_key) DO UPDATE SET
  permission_name = EXCLUDED.permission_name,
  module_key = EXCLUDED.module_key,
  updated_at = NOW();

INSERT INTO permission_definitions(permission_key, scope_type, module_key, screen_key, button_key, action_key, permission_name, description, risk_level, require_reason, require_mfa) VALUES
  ('pos.enter', 'tenant', 'pos', 'pos', 'None', 'enter', 'Vào POS', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('pos.open_register', 'tenant', 'pos', 'pos', 'None', 'open_register', 'Mở quầy POS', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('receipt.print', 'tenant', 'pos', 'receipt', 'None', 'print', 'In hóa đơn', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('shift.open', 'tenant', 'shift', 'shift', 'None', 'open', 'Mở ca', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('shift.close', 'tenant', 'shift', 'shift', 'None', 'close', 'Đóng ca', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('shift.view', 'tenant', 'shift', 'shift', 'None', 'view', 'Xem ca', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('order.view', 'tenant', 'order', 'order', 'None', 'view', 'Xem đơn hàng', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('order.create', 'tenant', 'order', 'order', 'None', 'create', 'Tạo đơn hàng', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('order.update_draft', 'tenant', 'order', 'order', 'None', 'update_draft', 'Sửa đơn nháp', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('order.cancel', 'tenant', 'order', 'order', 'None', 'cancel', 'Hủy đơn', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('order.void', 'tenant', 'order', 'order', 'None', 'void', 'Void đơn', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('order.complete', 'tenant', 'order', 'order', 'None', 'complete', 'Hoàn tất đơn', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('order.discount.apply', 'tenant', 'order', 'order', 'None', 'discount_apply', 'Áp giảm giá', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('order.price.override', 'tenant', 'order', 'order', 'None', 'price_override', 'Sửa giá tại POS', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('order.sell_on_credit', 'tenant', 'order', 'order', 'None', 'sell_on_credit', 'Bán công nợ', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('order.credit_override', 'tenant', 'order', 'order', 'None', 'credit_override', 'Vượt hạn mức công nợ', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('order.return', 'tenant', 'order', 'order', 'None', 'return', 'Trả hàng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('order.exchange', 'tenant', 'order', 'order', 'None', 'exchange', 'Đổi hàng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('order.split_bill', 'tenant', 'order', 'order', 'None', 'split_bill', 'Tách bill', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('order.merge_table', 'tenant', 'order', 'table', 'None', 'merge_table', 'Gộp bàn', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('order.move_table', 'tenant', 'order', 'table', 'None', 'move_table', 'Chuyển bàn', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('payment.view', 'tenant', 'payment', 'payment', 'None', 'view', 'Xem thanh toán', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('payment.process', 'tenant', 'payment', 'payment', 'None', 'process', 'Xử lý thanh toán', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('payment.partial', 'tenant', 'payment', 'payment', 'None', 'partial', 'Thanh toán một phần', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('payment.cash', 'tenant', 'payment', 'payment', 'None', 'cash', 'Thanh toán tiền mặt', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('payment.bank_transfer', 'tenant', 'payment', 'payment', 'None', 'bank_transfer', 'Thanh toán chuyển khoản', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('payment.card', 'tenant', 'payment', 'payment', 'None', 'card', 'Thanh toán thẻ', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('payment.e_wallet', 'tenant', 'payment', 'payment', 'None', 'e_wallet', 'Thanh toán ví', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('payment.voucher', 'tenant', 'payment', 'payment', 'None', 'voucher', 'Thanh toán voucher', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('payment.point', 'tenant', 'payment', 'payment', 'None', 'point', 'Thanh toán điểm', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('payment.refund', 'tenant', 'payment', 'payment', 'None', 'refund', 'Hoàn tiền', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('payment.refund_override', 'tenant', 'payment', 'payment', 'None', 'refund_override', 'Hoàn tiền vượt chính sách', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('payment.reconcile', 'tenant', 'payment', 'payment', 'None', 'reconcile', 'Đối soát thanh toán', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('receivable.view', 'tenant', 'receivable', 'receivable', 'None', 'view', 'Xem công nợ KH', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('receivable.create', 'tenant', 'receivable', 'receivable', 'None', 'create', 'Tạo công nợ KH', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('receivable.collect', 'tenant', 'receivable', 'receivable', 'None', 'collect', 'Thu công nợ KH', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('receivable.adjust', 'tenant', 'receivable', 'receivable', 'None', 'adjust', 'Điều chỉnh công nợ KH', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('receivable.write_off', 'tenant', 'receivable', 'receivable', 'None', 'write_off', 'Xóa nợ/xử lý nợ xấu', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('receivable.export', 'tenant', 'receivable', 'receivable', 'None', 'export', 'Xuất công nợ', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('store.view', 'tenant', 'store', 'store', 'None', 'view', 'Xem cửa hàng', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('store.create', 'tenant', 'store', 'store', 'None', 'create', 'Tạo cửa hàng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('store.update', 'tenant', 'store', 'store', 'None', 'update', 'Sửa cửa hàng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('store.disable', 'tenant', 'store', 'store', 'None', 'disable', 'Tắt cửa hàng', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('store.config.update', 'tenant', 'store', 'store', 'None', 'config_update', 'Sửa cấu hình cửa hàng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('store.device.bind', 'tenant', 'store', 'device', 'None', 'bind', 'Gán thiết bị POS', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('staff.view', 'tenant', 'staff', 'staff', 'None', 'view', 'Xem nhân viên', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('staff.create', 'tenant', 'staff', 'staff', 'None', 'create', 'Tạo nhân viên', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('staff.update', 'tenant', 'staff', 'staff', 'None', 'update', 'Sửa nhân viên', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('staff.disable', 'tenant', 'staff', 'staff', 'None', 'disable', 'Khóa nhân viên', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('staff.assign_store', 'tenant', 'staff', 'staff', 'None', 'assign_store', 'Gán nhân viên vào store', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('staff.assign_role', 'tenant', 'staff', 'staff', 'None', 'assign_role', 'Gán quyền nhân viên', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('staff.reset_pin', 'tenant', 'staff', 'staff', 'None', 'reset_pin', 'Reset PIN', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('staff.salary.view', 'tenant', 'staff', 'staff', 'None', 'salary_view', 'Xem lương', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('staff.salary.update', 'tenant', 'staff', 'staff', 'None', 'salary_update', 'Sửa lương', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('role.view', 'tenant', 'rbac', 'role', 'None', 'view', 'Xem role', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('role.create', 'tenant', 'rbac', 'role', 'None', 'create', 'Tạo role', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('role.update', 'tenant', 'rbac', 'role', 'None', 'update', 'Sửa role', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('role.assign_permission', 'tenant', 'rbac', 'role', 'None', 'assign_permission', 'Gán permission', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('product.view', 'tenant', 'product', 'product', 'None', 'view', 'Xem sản phẩm', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('product.create', 'tenant', 'product', 'product', 'None', 'create', 'Tạo sản phẩm', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('product.update', 'tenant', 'product', 'product', 'None', 'update', 'Sửa sản phẩm', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('product.delete', 'tenant', 'product', 'product', 'None', 'delete', 'Xóa sản phẩm', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('product.import', 'tenant', 'product', 'product', 'None', 'import', 'Import sản phẩm', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('product.export', 'tenant', 'product', 'product', 'None', 'export', 'Export sản phẩm', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('product.price.update', 'tenant', 'product', 'product', 'None', 'price_update', 'Sửa giá bán', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('product.cost.update', 'tenant', 'product', 'product', 'None', 'cost_update', 'Sửa giá vốn', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('product.barcode.manage', 'tenant', 'product', 'product', 'None', 'barcode_manage', 'Quản lý barcode', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('product.recipe.manage', 'tenant', 'product', 'product', 'None', 'recipe_manage', 'Quản lý recipe/BOM', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('product.lot.manage', 'tenant', 'product', 'product', 'None', 'lot_manage', 'Quản lý lô/hạn sử dụng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('product.serial.manage', 'tenant', 'product', 'product', 'None', 'serial_manage', 'Quản lý serial/IMEI', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('product.media.manage', 'tenant', 'product', 'product', 'None', 'media_manage', 'Quản lý media sản phẩm', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('promotion.view', 'tenant', 'promotion', 'promotion', 'None', 'view', 'Xem khuyến mãi', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('promotion.create', 'tenant', 'promotion', 'promotion', 'None', 'create', 'Tạo khuyến mãi', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('promotion.update', 'tenant', 'promotion', 'promotion', 'None', 'update', 'Sửa khuyến mãi', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('promotion.delete', 'tenant', 'promotion', 'promotion', 'None', 'delete', 'Xóa khuyến mãi', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('inventory.view', 'tenant', 'inventory', 'inventory', 'None', 'view', 'Xem tồn kho', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('inventory.view_cost', 'tenant', 'inventory', 'inventory', 'None', 'view_cost', 'Xem giá trị tồn kho', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('inventory.reserve', 'tenant', 'inventory', 'inventory', 'None', 'reserve', 'Giữ hàng', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('inventory.deduct', 'tenant', 'inventory', 'inventory', 'None', 'deduct', 'Trừ kho', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('inventory.adjust', 'tenant', 'inventory', 'inventory', 'None', 'adjust', 'Điều chỉnh kho', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('inventory.transfer', 'tenant', 'inventory', 'inventory', 'None', 'transfer', 'Chuyển kho', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('inventory.transfer.approve', 'tenant', 'inventory', 'inventory', 'None', 'transfer_approve', 'Duyệt chuyển kho', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('inventory.stocktake', 'tenant', 'inventory', 'inventory', 'None', 'stocktake', 'Kiểm kho', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('inventory.stocktake.approve', 'tenant', 'inventory', 'inventory', 'None', 'stocktake_approve', 'Chốt kiểm kho', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('inventory.transaction.view', 'tenant', 'inventory', 'inventory', 'None', 'transaction_view', 'Xem lịch sử kho', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('inventory.costing.view', 'tenant', 'inventory', 'inventory', 'None', 'costing_view', 'Xem costing', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('inventory.costing.adjust', 'tenant', 'inventory', 'inventory', 'None', 'costing_adjust', 'Điều chỉnh costing', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('purchase.view', 'tenant', 'purchase', 'purchase', 'None', 'view', 'Xem đơn nhập', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('purchase.create', 'tenant', 'purchase', 'purchase', 'None', 'create', 'Tạo đơn nhập', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('purchase.receive', 'tenant', 'purchase', 'purchase', 'None', 'receive', 'Nhận hàng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('purchase.cancel', 'tenant', 'purchase', 'purchase', 'None', 'cancel', 'Hủy đơn nhập', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('purchase.return', 'tenant', 'purchase', 'purchase', 'None', 'return', 'Trả hàng NCC', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('purchase.payable.view', 'tenant', 'purchase', 'purchase', 'None', 'payable_view', 'Xem công nợ NCC', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('purchase.payment.process', 'tenant', 'purchase', 'purchase', 'None', 'payment_process', 'Thanh toán NCC', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('supplier.view', 'tenant', 'supplier', 'supplier', 'None', 'view', 'Xem NCC', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('supplier.create', 'tenant', 'supplier', 'supplier', 'None', 'create', 'Tạo NCC', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('supplier.update', 'tenant', 'supplier', 'supplier', 'None', 'update', 'Sửa NCC', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('supplier.disable', 'tenant', 'supplier', 'supplier', 'None', 'disable', 'Khóa NCC', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('customer.view', 'tenant', 'customer', 'customer', 'None', 'view', 'Xem khách hàng', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('customer.create', 'tenant', 'customer', 'customer', 'None', 'create', 'Tạo khách hàng', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('customer.update', 'tenant', 'customer', 'customer', 'None', 'update', 'Sửa khách hàng', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('customer.disable', 'tenant', 'customer', 'customer', 'None', 'disable', 'Khóa khách hàng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('customer.merge', 'tenant', 'customer', 'customer', 'None', 'merge', 'Gộp khách hàng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('customer.export', 'tenant', 'customer', 'customer', 'None', 'export', 'Xuất khách hàng', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('customer.point.adjust', 'tenant', 'customer', 'customer', 'None', 'point_adjust', 'Điều chỉnh điểm', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('customer.consent.update', 'tenant', 'customer', 'customer', 'None', 'consent_update', 'Sửa consent', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('customer.campaign.manage', 'tenant', 'customer', 'campaign', 'None', 'manage', 'Quản lý chiến dịch', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('loyalty.view', 'tenant', 'loyalty', 'loyalty', 'None', 'view', 'Xem loyalty', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('loyalty.manage', 'tenant', 'loyalty', 'loyalty', 'None', 'manage', 'Quản lý loyalty', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('wallet.view', 'tenant', 'wallet', 'wallet', 'None', 'view', 'Xem ví khách hàng', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('wallet.adjust', 'tenant', 'wallet', 'wallet', 'None', 'adjust', 'Điều chỉnh ví khách hàng', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('report.sales.view', 'tenant', 'report', 'report', 'None', 'sales_view', 'Xem báo cáo doanh thu', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('report.inventory.view', 'tenant', 'report', 'report', 'None', 'inventory_view', 'Xem báo cáo kho', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('report.profit.view', 'tenant', 'report', 'report', 'None', 'profit_view', 'Xem báo cáo lợi nhuận', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('report.staff.view', 'tenant', 'report', 'report', 'None', 'staff_view', 'Xem báo cáo nhân viên', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('report.export', 'tenant', 'report', 'report', 'None', 'export', 'Xuất báo cáo', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('report.cost_profit.view', 'tenant', 'report', 'report', 'None', 'cost_profit_view', 'Xem giá vốn/lợi nhuận', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('invoice.view', 'tenant', 'invoice', 'invoice', 'None', 'view', 'Xem hóa đơn', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('invoice.create', 'tenant', 'invoice', 'invoice', 'None', 'create', 'Tạo hóa đơn', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('invoice.cancel', 'tenant', 'invoice', 'invoice', 'None', 'cancel', 'Hủy hóa đơn', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('invoice.credit_note.create', 'tenant', 'invoice', 'invoice', 'None', 'credit_note_create', 'Tạo credit note', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('cash.view', 'tenant', 'cash', 'cash', 'None', 'view', 'Xem quỹ', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('cash.movement.create', 'tenant', 'cash', 'cash', 'None', 'movement_create', 'Tạo giao dịch quỹ', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('cash.drawer.count', 'tenant', 'cash', 'cash', 'None', 'drawer_count', 'Đếm két', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('cash.drawer.reconcile', 'tenant', 'cash', 'cash', 'None', 'drawer_reconcile', 'Đối soát két', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('cash.bank_deposit', 'tenant', 'cash', 'cash', 'None', 'bank_deposit', 'Nộp tiền ngân hàng', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('finance.view', 'tenant', 'finance', 'finance', 'None', 'view', 'Xem tài chính', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('finance.journal.post', 'tenant', 'finance', 'finance', 'None', 'journal_post', 'Ghi bút toán', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('finance.period.lock', 'tenant', 'finance', 'finance', 'None', 'period_lock', 'Khóa kỳ', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('finance.period.reopen', 'tenant', 'finance', 'finance', 'None', 'period_reopen', 'Mở lại kỳ', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('setting.view', 'tenant', 'setting', 'setting', 'None', 'view', 'Xem cấu hình', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('setting.update', 'tenant', 'setting', 'setting', 'None', 'update', 'Sửa cấu hình', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('activity_log.view', 'tenant', 'audit', 'audit', 'None', 'view', 'Xem log hoạt động', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('approval.view', 'tenant', 'approval', 'approval', 'None', 'view', 'Xem yêu cầu duyệt', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('approval.approve', 'tenant', 'approval', 'approval', 'None', 'approve', 'Duyệt yêu cầu', 'Full new DB business permission', 'critical', TRUE, TRUE),
  ('approval.reject', 'tenant', 'approval', 'approval', 'None', 'reject', 'Từ chối yêu cầu', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('notification.view', 'tenant', 'notification', 'notification', 'None', 'view', 'Xem thông báo', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('notification.send', 'tenant', 'notification', 'notification', 'None', 'send', 'Gửi thông báo', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('channel.view', 'tenant', 'channel', 'channel', 'None', 'view', 'Xem kênh bán', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('channel.manage', 'tenant', 'channel', 'channel', 'None', 'manage', 'Quản lý kênh bán', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('channel.sync', 'tenant', 'channel', 'channel', 'None', 'sync', 'Đồng bộ kênh bán', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('shipping.view', 'tenant', 'shipping', 'shipping', 'None', 'view', 'Xem vận chuyển', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('shipping.create', 'tenant', 'shipping', 'shipping', 'None', 'create', 'Tạo shipment', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('shipping.update', 'tenant', 'shipping', 'shipping', 'None', 'update', 'Cập nhật shipment', 'Full new DB business permission', 'medium', FALSE, FALSE),
  ('shipping.cod_reconcile', 'tenant', 'shipping', 'shipping', 'None', 'cod_reconcile', 'Đối soát COD', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('service.view', 'tenant', 'service', 'service', 'None', 'view', 'Xem dịch vụ/bảo hành', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('service.manage', 'tenant', 'service', 'service', 'None', 'manage', 'Quản lý dịch vụ/bảo hành', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('warranty.claim.process', 'tenant', 'service', 'warranty', 'None', 'claim_process', 'Xử lý bảo hành', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('production.view', 'tenant', 'production', 'production', 'None', 'view', 'Xem sản xuất/bếp', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('production.manage', 'tenant', 'production', 'production', 'None', 'manage', 'Quản lý sản xuất/bếp', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('waste.create', 'tenant', 'production', 'waste', 'None', 'create', 'Ghi nhận hao hụt', 'Full new DB business permission', 'high', TRUE, FALSE),
  ('kitchen.view', 'tenant', 'kitchen', 'kitchen', 'None', 'view', 'Xem bếp', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('kitchen.update', 'tenant', 'kitchen', 'kitchen', 'None', 'update', 'Cập nhật trạng thái bếp', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('table.view', 'tenant', 'table', 'table', 'None', 'view', 'Xem bàn', 'Full new DB business permission', 'low', FALSE, FALSE),
  ('table.manage', 'tenant', 'table', 'table', 'None', 'manage', 'Quản lý bàn', 'Full new DB business permission', 'medium', FALSE, FALSE)
ON CONFLICT (permission_key) DO UPDATE SET
  scope_type = EXCLUDED.scope_type,
  module_key = EXCLUDED.module_key,
  screen_key = EXCLUDED.screen_key,
  button_key = EXCLUDED.button_key,
  action_key = EXCLUDED.action_key,
  permission_name = EXCLUDED.permission_name,
  description = EXCLUDED.description,
  risk_level = EXCLUDED.risk_level,
  require_reason = EXCLUDED.require_reason,
  require_mfa = EXCLUDED.require_mfa;

-- OWNER and ADMIN get all business permissions
INSERT INTO role_permissions(role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON TRUE
WHERE r.role_key IN ('OWNER','ADMIN')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- CASHIER default permissions
INSERT INTO role_permissions(role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.permission_key = ANY(ARRAY[
  'pos.enter','receipt.print','shift.view','shift.open','shift.close','order.view','order.create','order.update_draft','order.complete','order.discount.apply','payment.view','payment.process','payment.partial','payment.cash','payment.bank_transfer','payment.card','payment.e_wallet','payment.voucher','payment.point','customer.view','customer.create','customer.update','product.view','inventory.view','table.view','kitchen.view'
]) WHERE r.role_key = 'CASHIER'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- INVENTORY default permissions
INSERT INTO role_permissions(role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.permission_key = ANY(ARRAY[
  'product.view','inventory.view','inventory.view_cost','inventory.reserve','inventory.adjust','inventory.transfer','inventory.stocktake','inventory.transaction.view','purchase.view','purchase.create','purchase.receive','purchase.return','supplier.view','supplier.create','supplier.update','report.inventory.view','activity_log.view'
]) WHERE r.role_key = 'INVENTORY'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- KITCHEN default permissions
INSERT INTO role_permissions(role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.permission_key = ANY(ARRAY[
  'kitchen.view','kitchen.update','order.view','table.view','production.view','waste.create'
]) WHERE r.role_key = 'KITCHEN'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- DELIVERY default permissions
INSERT INTO role_permissions(role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.permission_key = ANY(ARRAY[
  'shipping.view','shipping.update','order.view','customer.view','payment.cash','receivable.collect'
]) WHERE r.role_key = 'DELIVERY'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- STAFF default permissions
INSERT INTO role_permissions(role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.permission_key = ANY(ARRAY[
  'product.view','customer.view','order.view','inventory.view','activity_log.view'
]) WHERE r.role_key = 'STAFF'
ON CONFLICT (role_id, permission_id) DO NOTHING;
